version: '3'
services:
  app:
    image: dyoshikawa/rails:latest
    volumes:
      - .:/myproject
    tty: true
    command: /bin/bash
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: dyoshikawa/mysql:latest
    user: "1000:50"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: development
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
